-- VHDL Entity my_project_lib.lab6.symbol
--
-- Created:
--          by - fzhang19.ews (eceb-2022-44.ews.illinois.edu)
--          at - 11:41:19 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lab6 IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END lab6 ;

--
-- VHDL Architecture my_project_lib.lab6.struct
--
-- Created:
--          by - fzhang19.ews (eceb-2022-44.ews.illinois.edu)
--          at - 11:41:19 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF lab6 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_7' of 'inv'
   dout1 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_8' of 'inv'
   dout4 <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_11' of 'inv'
   dout <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_0' of 'nand'
   A <= NOT(dout2 AND dout3);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'nand'
   dout2 <= NOT(dout1 AND dout4);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   dout3 <= NOT(S2 AND dout);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'nor'
   P <= NOT(dout5 OR dout6 OR dout7);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'nor'
   dout5 <= NOT(S0 OR S1);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'nor'
   dout6 <= NOT(S2 OR dout4);

   -- ModuleWare code(v1.9) for instance 'U_6' of 'nor'
   dout7 <= NOT(dout1 OR S0);

   -- Instance port mappings.

END struct;
