-- VHDL Entity my_project_lib.next_state_table.symbol
--
-- Created:
--          by - fzhang19.ews (eceb-2022-44.ews.illinois.edu)
--          at - 11:41:19 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY next_state_table IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      T  : IN     std_logic;
      O0 : OUT    std_logic;
      O1 : OUT    std_logic;
      O2 : OUT    std_logic
   );

-- Declarations

END next_state_table ;

--
-- VHDL Architecture my_project_lib.next_state_table.struct
--
-- Created:
--          by - fzhang19.ews (eceb-2022-44.ews.illinois.edu)
--          at - 11:41:19 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF next_state_table IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'and'
   O1 <= S2 AND dout;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   O0 <= dout1 AND dout2;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'inv'
   dout <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout2 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout1 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'inv'
   dout3 <= NOT(T);

   -- ModuleWare code(v1.9) for instance 'U_6' of 'inv'
   O2 <= NOT(dout3);

   -- Instance port mappings.

END struct;
